endpoint:
  host: "0.0.0.0"
  port: 8081
  token: "test-token"
adapter:
  ispc:
    url: "http://172.16.30.28:7080"
    agent_login: "brt_online_agent"
    secret: "123"
    timeout: 10
  cft:
    url: "http://172.16.30.28:90"
    timeout: 10  
card:
  pans: ["505827082","505827083"]    